### ISSUE TITLE
The cache may cause confusion when creating constants via the KB API

### ISSUE THREAD

**Issue by JLMoszkowicz** [cycorp/api-suite#3]
Consider the following scenario:  You want to add some new constants to the KB along with some basic information about those constants.  For example, say you want to create NewConstant and assert (isa NewConstant ExistingCollection).  This is a pretty straightforward thing to do, but the user can run into trouble if they don't know what type of thing NewCosntant should be (i.e., an individual or a collection).  In this scenario, the user first declares that NewConstant is a KBIndividual and tries to assert the instance assertion.  This doesn't work though because it turns out that ExistingCollection is actually a SecondOrderCollection, so NewConstant has to be a KBCollection instead.  The user goes into the KB and kills NewConstant the KBIndividual so that the API can create NewConstant the KBCollection.  At this point, it seems like everything should work, but it seems as if the cache holds onto the idea that NewConstant is already a KBTerm, so it cannot be a KBCollection.  It's pretty confusing that the cache would hold onto this even after NewConstant has been removed from the KB.  The workaround seemed to be to declare the KBCollection in the simplest way possible:

KBCollection newC = KBCollectionImpl.findOrCreate("NewConstant");

After doing that, the user can assert the isa directly using FactImpl.findOrCreate.  It seems as if the caching problem comes up if you try to use fancier versions of KBCollectionImpl.findOrCreate that try to do the creation and the assertion in one fell swoop.

**Comment by vijayatcyc** [comment]
The KB API stores only one representation of a concept in the cache. That is, if the user "gets" an individual, like so:

KBIndividual i = KBIndividualImpl.get("UniversalVocabularyMt")

The API proactively tightens down the concept to Context.class. But it is type cast to KBIndividual, since it is a super class of Context. So if later in the code, if the user expects a Context for "UniversalVocabularyMt" and gets it, like so:

Context c = Context.get("UniversalVocabularyMt")

then,

c == i, they are pointer equal, the same object. 

Because of this,

if you create a new object, 

KBIndividual newInd = KBIndividual.findOrCreate("NewContext");

The API has created a new Individual, and has stored in the cache as a KBIndividual. 

But later, if the users calls:

Context newCtx = Context.findOrCreate("NewContext"), the API throws an exception, saying that the KBIndividual cannot be cast to Context. 

This is the most likely reason this exception will be encountered. 

The description of this post is a similar scenario, but has a minor difference. If a term is deleted outside of the API, the API cache would not know about it. If the user deletes the concept from .delete() command, cast exceptions would not happen.

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#3
